services:
  - type: web
    name: donation-backend
    env: node
    region: oregon
    plan: free
    nodeVersion: 18.17.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://crowd-fund-zeta.vercel.app 